# Generated by Django 4.2.5 on 2023-10-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0002_tag_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="app_blog.tag"),
        ),
    ]
